### ISSUE TITLE
Email coming from the Gallery is not formatted properly

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShellGallery#204]
Email coming from the Gallery is not formatted properly, or is formatted in a way that gets mangled in transit.

I recently needed to contact a package owner. Here is the copy of the email I received. It looks like there is a mix of markdown and html here and neither is being rendered properly.

```
From: Config Gallery Admin <cgadmin@microsoft.com> 
Sent: Wednesday, November 17, 2021 7:05 AM
To: Sean Wheeler <Sean.Wheeler@microsoft.com>
Subject: [PowerShell Gallery] Message for owners of the package 'AzureAD' [Sender Copy]

You sent the following message via PowerShell Gallery: 

_User sewhee &lt;sewhee@microsoft.com&gt; sends the following message to the owners of Package '[AzureAD 2.0.2.140](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.powershellgallery.com%2Fpackages%2FAzureAD%2F2.0.2.140&amp;data=04%7C01%7CSean.Wheeler%40microsoft.com%7Cd7cc112938c54eee8e1308d9a9caddc6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637727511043067588%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&amp;sdata=S21TeJjatBmRZaYhal8rNEqOMrPYHkYWMzXfkcRKV9Y%3D&amp;reserved=0)'._

The ProjectURI in the module manifest returns 404. Please update the URI to point to the current docs location:
https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fpowershell%2Fmodule%2Fazuread&amp;data=04%7C01%7CSean.Wheeler%40microsoft.com%7Cd7cc112938c54eee8e1308d9a9caddc6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637727511043067588%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&amp;sdata=JevQeee3kQo8XhQWLtnaNC7P7TsYeCbvIEtIlomOchk%3D&amp;reserved=0

-----------------------------------------------
<em style="font-size: 0.8em;">
    To stop receiving contact emails as an owner of this package, sign in to the PowerShell Gallery and
    [change your email notification settings](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.powershellgallery.com%2Faccount&amp;data=04%7C01%7CSean.Wheeler%40microsoft.com%7Cd7cc112938c54eee8e1308d9a9caddc6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637727511043067588%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&amp;sdata=LL17RIVxMD%2BhAAGbc%2BndKzSPFom%2BWO3LwxQeR%2FC47z4%3D&amp;reserved=0).
</em>
```

**Comment by sdwheeler** [comment]
I just published an update to a module and received the following email:

```
From: Config Gallery Admin <cgadmin@microsoft.com> 
Sent: Wednesday, November 17, 2021 1:20 PM
To: Sean Wheeler <Sean.Wheeler@microsoft.com>
Subject: [PowerShell Gallery] Package published - sdwheeler.DocsHelpers 1.0.5

The package [sdwheeler.DocsHelpers 1.0.5](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.powershellgallery.com%2Fpackages%2Fsdwheeler.DocsHelpers%2F1.0.5&amp;data=04%7C01%7CSean.Wheeler%40microsoft.com%7C421941991b454f025b5a08d9a9ff50f1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637727736317419644%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&amp;sdata=P7F1a4arR62NDsTn6tPvVPruJdB%2FJuKzYLDhtPsMhzA%3D&amp;reserved=0) was recently published on PowerShell Gallery by sewhee. If this was not intended, please [contact support](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.powershellgallery.com%2Fpackages%2Fsdwheeler.DocsHelpers%2F1.0.5%2FReportMyPackage&amp;data=04%7C01%7CSean.Wheeler%40microsoft.com%7C421941991b454f025b5a08d9a9ff50f1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637727736317429600%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&amp;sdata=HkshwkHJxGyhQatB8%2FPLhKZyZAeSz5Wh%2F6lgUUK%2B%2FAM%3D&amp;reserved=0).

-----------------------------------------------
<em style="font-size: 0.8em;">
    To stop receiving emails as an owner of this package, sign in to the PowerShell Gallery and
    [change your email notification settings](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.powershellgallery.com%2Faccount&amp;data=04%7C01%7CSean.Wheeler%40microsoft.com%7C421941991b454f025b5a08d9a9ff50f1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637727736317429600%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&amp;sdata=GCjN%2BIUdofj7TPXNh8KRJ9BAmf31zZF3%2FxQcNtNiEPo%3D&amp;reserved=0).
</em>
```

**Comment by asheroto** [comment]
In Outlook, all other e-mails show up normally. Looks like the issue is that it's encoding the message with a `Content-Type: text/plain` which makes the e-mail client think it's text-only.

![image](https://github.com/PowerShell/PowerShellGallery/assets/49938263/a061353a-dc22-4989-b672-d7a27c89f14e)

**Comment by fflaten** [comment]
Still broken in 2024.

Minor quality issues like this and broken verification links going unresolved for years reflects poorly on the PowerShell ecosystem and community. We can't expect quality packages from authors when the gallery itself is broken like this. I really hope PowerShell Gallery can get some much needed attention soon. Or maybe open source it like NugetGallery. /cc @SydneyhSmith
