### ISSUE TITLE
Can't access 'Account Settings'

### ISSUE THREAD

**Issue by lazywinadmin** [PowerShell/PowerShellGallery#52]
I noticed some odd things with my PowerShell Gallery Account today.

I can't:
* Access `Account Settings`, it returns `500 - Internal Server Error`

I can:
* Authenticate with my outlook account (2FA)
* manage my packages, manage API keys etc..
* Repro in Incognito

Also I noticed a different email address when i click on my profile 😝 (mine is `fxa....@outlook.com`)
![image](https://user-images.githubusercontent.com/3020909/55042679-d4f33f00-4fef-11e9-9a0e-592b4c57d10f.png)

I don't think my account got compromised.

Anybody can repro ?

**Comment by edyoung** [comment]
Your account has not been compromised. We accidentally messed something up during database maintenance which led to this incorrect email address showing for many users - will be corrected soon.

I'm not sure why you're seeing a 500 error, will need to look into that. Cc @alerickson

**Comment by lazywinadmin** [comment]
Thanks @edyoung

@alerickson let me know if you want me to provide other information

**Comment by SydneyhSmith** [comment]
@lazywinadmin the issue should now be resolved so I am closing this issue, please let us know if you are still hitting this and we will reopen/investigate

**Comment by lazywinadmin** [comment]
@SydneyhSmith Thanks I can see my account properly now 
However I still have an issue to access "account settings", Error 500 see the second screenshot.

profile looks good now:
![image](https://user-images.githubusercontent.com/3020909/55263369-f80b3200-522d-11e9-80a9-d2f69299eb50.png)

Trying to access "Account Settings":

![image](https://user-images.githubusercontent.com/3020909/55263247-964ac800-522d-11e9-9168-a064f66fe358.png)

**Comment by SydneyhSmith** [comment]
@lazywinadmin thanks, I am able to re-produce this and have re-opened the issue, we will investigate.

**Comment by SydneyhSmith** [comment]
The fix is now live, thanks!
